# Site settings (baseurl must end with a trailing slash!)
baseurl = "https://gostack-io.github.io/"
title = "gostack.io"
languageCode = "en-us"
theme = "hugo-universal-theme"
copyright = "Copyright &#169; tobybot11"

# The theme uses pagination for post, gallery, and project listings.
#paginate = 12

# The theme supports disqus, which will appear only on deployed sites,
# not locally when run with `hugo server`; as with standard Hugo disqus,
# you can specify disqus_identifier, disqus_title, and disqus_url in the
# front matter of specific content.
disqusShortname = "tobybot11-io"

[menu]

[[menu.main]]
    name = "Home"
    url  = "/"
    weight = 1

[params]
    style = "red"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io email
    # TODO - make a gostack.io email server before doing thisr
    email = "toby.ford@pobox.com"

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

[params.widgets]
    categories = true
    tags = true
    search = true

[params.carousel]
    enable = true

[params.recent_posts]
    enable = true
    title = "from our blog"
    subtitle = "oven"

[params.see_more]
    enable = true
    icon = "fa fa-file-code-o"
    title = "do you want to see more?"
    subtitle = "check out our Git repo."
    link_url = "https://github.com/gostack-io"
    link_text = "github repo"
